### ISSUE TITLE
Common UIs / Navigation Component(menu)

### ISSUE THREAD

**Issue by blarzHernandez** [chingu-voyage4/Geckos-Team-25#15]
Create:

- [ ] Navigation Component(Navigation.js)

It looks like this:
![Navigation-js.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a860ad13e81ac0012197b40/125516c66e82c728ace21e0d46c6958c2a8582bd86e6b10eae4eb2d86b56357c2301a03f32dfa17dbe1a79520b0e1af9140e5a47fef98929a3e23c748b0d09ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98b45c7ec3425e6838a483a0c48.JPG)

**Comment by kenitohenry** [comment]
@blarzHernandez  this picture, is this the menu? where my mouse is hovering over?
