### ISSUE TITLE
#6— Define the MVP

### ISSUE THREAD

**Issue by blarzHernandez** [chingu-voyage4/Geckos-Team-25#3]
Goal: Hold a meeting to decide on the minimum viable product (MVP).
-Front End - consider the views and their associated functionality
-Back End - consider the endpoints, routes and associated logic.
-Database - consider the complexity of the database and associated models.
-Deployment - consider how / where you will host the project

**Comment by corochena** [comment]
As a user...
I am able to create new boards (board has a name and background color)
Inside a board I can create a list (list has a name)
Inside a board I can move a list across the board (to the right or to the left)
Inside a list I am able to add a card (card has a name, description, attachment and label)
I can see

**Comment by blarzHernandez** [comment]
Google Doc - About MVP..
https://docs.google.com/document/d/11s5jkw7piTccTkUTfnJduWHWTuXFv-2Ii5d6P-QSWwI/edit

**Comment by kenitohenry** [comment]
The document that you are sharing @blarzHernandez  is the features of trello, i think the list @corochena has is what would be considered an MVP like the minimum we aiming for
